=== kdturkar/XML-schema-for-a-doctor-and-patient-profiles/Hospital XML-DTD/Data.dtd
<?xml encoding="utf-8"?>

<!ELEMENT Hospital (Doctors,Patients,Appointments)>
<!ATTLIST Hospital
    xmlns CDATA #FIXED ''>

<!ELEMENT Doctors (Doctor)+>
<!ATTLIST Doctors
    xmlns CDATA #FIXED ''>

<!ELEMENT Patients (Patient)+>
<!ATTLIST Patients
    xmlns CDATA #FIXED ''>

<!ELEMENT Appointments (Appointment)+>
<!ATTLIST Appointments
    xmlns CDATA #FIXED ''>

<!ELEMENT Doctor (Doctor_Name,DoctorContact,DOB,Specialization,(AppointmentsInADay|PatientAppointments))>
<!ATTLIST Doctor
    xmlns CDATA #FIXED ''
    D_Id CDATA #REQUIRED>

<!ELEMENT Patient (Patient_Name,PatientContact,DOB,AttendedDoctor,Illness)>
<!ATTLIST Patient
    xmlns CDATA #FIXED ''
    P_Id CDATA #REQUIRED>

<!ELEMENT Appointment (AppointedDoctor,AppointedPatient,AppointedDate,AppointedTime,PatientCondition)>
<!ATTLIST Appointment
    xmlns CDATA #FIXED ''
    AppointmentId CDATA #REQUIRED>

<!ELEMENT Doctor_Name (#PCDATA)>
<!ATTLIST Doctor_Name
    xmlns CDATA #FIXED ''>

<!ELEMENT DoctorContact (DoctorAddress,DoctorPhone+)>
<!ATTLIST DoctorContact
    xmlns CDATA #FIXED ''>

<!ELEMENT Specialization (#PCDATA)>
<!ATTLIST Specialization
    xmlns CDATA #FIXED ''>

<!ELEMENT AppointmentsInADay EMPTY>
<!ATTLIST AppointmentsInADay
    xmlns CDATA #FIXED ''>

<!ELEMENT PatientAppointments EMPTY>
<!ATTLIST PatientAppointments
    xmlns CDATA #FIXED ''>

<!ELEMENT Patient_Name (#PCDATA)>
<!ATTLIST Patient_Name
    xmlns CDATA #FIXED ''>

<!ELEMENT PatientContact (PatientAddress,PatientPhone+)>
<!ATTLIST PatientContact
    xmlns CDATA #FIXED ''>

<!ELEMENT AttendedDoctor EMPTY>
<!ATTLIST AttendedDoctor
    xmlns CDATA #FIXED ''
    AttendedBy CDATA #REQUIRED>

<!ELEMENT Illness (#PCDATA)>
<!ATTLIST Illness
    xmlns CDATA #FIXED ''>

<!ELEMENT AppointedDoctor EMPTY>
<!ATTLIST AppointedDoctor
    xmlns CDATA #FIXED ''
    AppointedDoctorId CDATA #REQUIRED>

<!ELEMENT AppointedPatient EMPTY>
<!ATTLIST AppointedPatient
    xmlns CDATA #FIXED ''
    AppointedPatientId CDATA #REQUIRED>

<!ELEMENT AppointedDate EMPTY>
<!ATTLIST AppointedDate
    xmlns CDATA #FIXED ''
    AppointmentDate NMTOKEN #REQUIRED>

<!ELEMENT AppointedTime EMPTY>
<!ATTLIST AppointedTime
    xmlns CDATA #FIXED ''
    AppointmentTime NMTOKEN #REQUIRED>

<!ELEMENT PatientCondition (#PCDATA)>
<!ATTLIST PatientCondition
    xmlns CDATA #FIXED ''>

<!ELEMENT DoctorAddress (#PCDATA)>
<!ATTLIST DoctorAddress
    xmlns CDATA #FIXED ''>

<!ELEMENT DoctorPhone (#PCDATA)>
<!ATTLIST DoctorPhone
    xmlns CDATA #FIXED ''>

<!ELEMENT PatientAddress (#PCDATA)>
<!ATTLIST PatientAddress
    xmlns CDATA #FIXED ''>

<!ELEMENT PatientPhone (#PCDATA)>
<!ATTLIST PatientPhone
    xmlns CDATA #FIXED ''>

<!ELEMENT DOB (#PCDATA)>
<!ATTLIST DOB
    xmlns CDATA #FIXED ''>

=== kdturkar/XML-schema-for-a-doctor-and-patient-profiles/Hospital XML-DTD/Data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Data_Style.xsl"?>
<!DOCTYPE Hospital SYSTEM "Data.dtd">
<Hospital>
    <Doctors>
        <Doctor D_Id="01">
            <Doctor_Name> Dr.Rajiv Chaudhary </Doctor_Name>
            <DoctorContact>
                <DoctorAddress>Chanakyapuri Building tukaram paduka chowk 1st floor , Pune - 411005</DoctorAddress>
                <DoctorPhone>+919467346596/</DoctorPhone>
                <DoctorPhone> +918467346592/</DoctorPhone>
                <DoctorPhone> +918767346596</DoctorPhone>
            </DoctorContact>
            <DOB> 1975-06-01 </DOB>
            <Specialization> Orthopedics </Specialization>
            <AppointmentsInADay />
        </Doctor>

        <Doctor D_Id="02">
            <Doctor_Name> Dr.Satish Yadav </Doctor_Name>
            <DoctorContact>
                <DoctorAddress>1160/61, University Rd, Revenue Colony, Shivajinagar , Pune - 411005</DoctorAddress>
                <DoctorPhone>+918785588594/</DoctorPhone>
                <DoctorPhone> +919785588594</DoctorPhone>
            </DoctorContact>
            <DOB> 1970-10-22 </DOB>
            <Specialization> Ayurvedic </Specialization>
            <PatientAppointments />
        </Doctor>
    </Doctors>

    <Patients>
        <Patient P_Id="01">
            <Patient_Name> Prabha Rane </Patient_Name>
            <PatientContact>
                <PatientAddress>Shri Ram Nagar, Tumsar, Bhandara</PatientAddress>
                <PatientPhone>+917785588594/</PatientPhone>
                <PatientPhone> +919185588995</PatientPhone>
            </PatientContact>
            <DOB> 1988-06-09 </DOB>
            <AttendedDoctor AttendedBy="Dr.Satish Yadav" />
            <Illness> Chronic Disease </Illness>
        </Patient>

        <Patient P_Id="02">
            <Patient_Name> Ravi Teja </Patient_Name>
            <PatientContact>
                <PatientAddress>Vinoba Nagar, Tumsar, Bhandara</PatientAddress>
                <PatientPhone>+919785588594/</PatientPhone>
                <PatientPhone> +919345558851</PatientPhone>
            </PatientContact>
            <DOB> 1987-06-03 </DOB>
            <AttendedDoctor AttendedBy="Dr.Rajiv Chaudhary" />
            <Illness> Diabeties </Illness>
        </Patient>
    </Patients>

    <Appointments>
        <Appointment AppointmentId="01">
            <AppointedDoctor AppointedDoctorId="02" />
            <AppointedPatient AppointedPatientId="01" />
            <AppointedDate AppointmentDate="2023-02-12" />
            <AppointedTime AppointmentTime="09:00:00" />
            <PatientCondition>Serious</PatientCondition>
        </Appointment>
        <Appointment AppointmentId="02">
            <AppointedDoctor AppointedDoctorId="01" />
            <AppointedPatient AppointedPatientId="02" />
            <AppointedDate AppointmentDate="2023-02-20" />
            <AppointedTime AppointmentTime="10:00:00" />
            <PatientCondition>Normal</PatientCondition>
        </Appointment>
    </Appointments>
</Hospital>
